default: &default
  provider: mysql
  port: 3306

production:
  <<: *default
  host: localhost
  user: root
  password: xpto1234
  database: ssp_go

development:
  <<: *default
  host: tcc.covp4olpix00.sa-east-1.rds.amazonaws.com
  user: root
  password: xpto1234
  database: tcc
#  host: localhost
#  user: root
#  password: xpto1234
#  database: ssp_go